plugins: [jekyll-paginate]

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Collections
collections_dir: hq
collections:
  wins:
      output: true
      permalink: /wins/:name/
  milestones:
      output: true
      permalink: /milestones/:name/
  projects:
      output: true
      permalink: /projects/:name/
  reflections:
      output: true
      permalink: /reflections/:name/
  systems:
      output: true
      permalink: /systems/:name/
  goals:
      output: true
      permalink: /goals/:name/

# Setup
title:            The War
tagline:          'build a better person.'
description:      'fighting a war against comfort, mediocrity and tradition in public.'
url:              http://nibirsan.org/war-of-becoming/
baseurl:          /

author:
  name:           'Nibir Sankar'
  url:            https://nibirsan.org/

paginate:         5

github:
  repo:           https://github.com/moisentinel/war-of-becoming/
